apiVersion: apps/v1
kind: Deployment
metadata:
  name: mfsa-clstr
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
        - name: mfsa-clstr
          image: 045298372198.dkr.ecr.us-east-1.amazonaws.com/mfsa-adapter-repo:latest
          ports:
            - containerPort: 8085
      restartPolicy: Always
